# This dockerfile is specific to building the OpenShift CNF sctp tester image
FROM openshift/origin-release:golang-1.13 as builder

# Add everything
ENV PKG_NAME=github.com/openshift-kni/cnf-features-deploy
ENV PKG_PATH=/go/src/$PKG_NAME
ENV TESTER_PATH=$PKG_PATH/cnf-tests/testimages/sctptester

RUN mkdir -p $PKG_PATH

COPY . $PKG_PATH/
WORKDIR $TESTER_PATH

RUN go build -mod=vendor -o /sctptest

FROM openshift/origin-base

COPY --from=builder /sctptest /usr/bin/sctptest
RUN dnf install -y lksctp-tools

LABEL io.openshift.tags="openshift" \
      maintainer="Federico Paolinelli <fpaoline@redhat.com>"

CMD ["/usr/bin/sctptest"]
