#!/bin/bash

. $(dirname "$0")/components.sh
. $(dirname "$0")/check-skipped-files.sh

# check if we must skip any check for files in staging
filenames=$(git diff --name-only --cached)
echo checking staging filenames: $filenames

check_skipped_files $filenames
if [ $? -eq 0 ]; then
    echo "Files checks were skipped for staging"
    exit 0
else
    echo "No files checks were skipped for staging"
fi

# check format
if ! [[ "$(head -1 $1)t sh" == *":"* ]]; then
        echo ERROR: commit msg subject must include component name
	exit 4
fi

msg_prefix=$(head -1 $1 | cut -d':' -f 1)
if ! [ ${components[$msg_prefix]+exist} ]; then
	printf -v components_string '%s/' "${!components[@]}"
	echo "ERROR: must use authorized component (${components_string%/})"
	exit 8
fi

# check prefixes
exceptions=( README.md )
for filename in $filenames; do
	if [[ ! " ${exceptions[@]} " =~ " $filename " ]]; then
		is_prefix_found=false
		IFS=', ' read -r -a prefixes <<< "${components[$msg_prefix]}"
		for prefix in "${prefixes[@]}"; do
			if [[ "$filename" == "$prefix"* ]]; then
				is_prefix_found=true
				break
			fi
		done
		if [ "$is_prefix_found" = false ]; then
			echo ERROR: $filename is not part of $msg_prefix component
			for component in "${!components[@]}"; do
				IFS=', ' read -r -a prefixes <<< "${components[$component]}"
				for prefix in "${prefixes[@]}"; do
					if [[ "$filename" == "$prefix"* ]]; then
						echo INFO: consider using $component as prefix
					fi
				done
			done
			exit 12
		fi
	fi
done
