apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: 02-worker-
resources:
- ../container-private-mounts
labels:
- includeSelectors: true
  pairs:
    machineconfiguration.openshift.io/role: worker
